#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dnspython
Version  : 1.15.0
Release  : 29
URL      : http://pypi.debian.net/dnspython/dnspython-1.15.0.zip
Source0  : http://pypi.debian.net/dnspython/dnspython-1.15.0.zip
Summary  : DNS toolkit
Group    : Development/Tools
License  : ISC
Requires: dnspython-legacypython
Requires: dnspython-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
record types. It can be used for queries, zone transfers, and dynamic
        updates.  It supports TSIG authenticated messages and EDNS0.
        
        dnspython provides both high and low level access to DNS. The high
        level classes perform queries for data of a given name, type, and
        class, and return an answer set.  The low level classes allow
        direct manipulation of DNS zones, messages, names, and records.

%package legacypython
Summary: legacypython components for the dnspython package.
Group: Default

%description legacypython
legacypython components for the dnspython package.


%package python
Summary: python components for the dnspython package.
Group: Default
Requires: dnspython-legacypython

%description python
python components for the dnspython package.


%prep
%setup -q -n dnspython-1.15.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505001928
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd tests ; make test
%install
export SOURCE_DATE_EPOCH=1505001928
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
/usr/lib/python3*/*
