#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dnspython
Version  : 1.14.0
Release  : 20
URL      : http://pypi.debian.net/dnspython/dnspython-1.14.0.zip
Source0  : http://pypi.debian.net/dnspython/dnspython-1.14.0.zip
Summary  : DNS toolkit
Group    : Development/Tools
License  : ISC
Requires: dnspython-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
dnspython [![Build Status](https://travis-ci.org/rthalley/dnspython.svg?branch=master)](https://travis-ci.org/rthalley/dnspython)

%package python
Summary: python components for the dnspython package.
Group: Default

%description python
python components for the dnspython package.


%prep
%setup -q -n dnspython-1.14.0

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd tests ; make test
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
